"""Initial migration with updated order model

Revision ID: 1f86f885b954
Revises: 87aec34d086c
Create Date: 2025-07-23 09:55:22.875999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f86f885b954'
down_revision: Union[str, Sequence[str], None] = '87aec34d086c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courier', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courier', type_='unique')
    # ### end Alembic commands ###
