"""Initial migration with updated order model

Revision ID: 298bb0d0d44d
Revises: 933a50f06a67
Create Date: 2025-07-23 01:24:27.426847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298bb0d0d44d'
down_revision: Union[str, Sequence[str], None] = '933a50f06a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('delivery_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier', 'delivery_rate')
    # ### end Alembic commands ###
