"""add is_subscription_extended to order

Revision ID: 2c5faeb27078
Revises: 5c5a0163e3f3
Create Date: 2025-07-05 06:00:44.838817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5faeb27078'
down_revision: Union[str, Sequence[str], None] = '5c5a0163e3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_subscription_extended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'is_subscription_extended')
    # ### end Alembic commands ###
