"""add denormalized bouquet fields to order and delivery

Revision ID: 3b07d08d6c27
Revises: 10328ad9bdd7
Create Date: 2025-07-03 22:50:45.490051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b07d08d6c27'
down_revision: Union[str, Sequence[str], None] = '10328ad9bdd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('bouquet_size', sa.String(length=16), nullable=True))
    op.add_column('delivery', sa.Column('delivery_type', sa.String(length=32), nullable=True))
    op.add_column('delivery', sa.Column('price_at_delivery', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('bouquet_size', sa.String(length=16), nullable=True))
    op.add_column('order', sa.Column('delivery_type', sa.String(length=32), nullable=True))
    op.add_column('order', sa.Column('price_at_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'price_at_order')
    op.drop_column('order', 'delivery_type')
    op.drop_column('order', 'bouquet_size')
    op.drop_column('delivery', 'price_at_delivery')
    op.drop_column('delivery', 'delivery_type')
    op.drop_column('delivery', 'bouquet_size')
    # ### end Alembic commands ###
