"""add preferences to delivery

Revision ID: 42e5784b0e64
Revises: 4912d6ea2621
Create Date: 2025-07-05 22:14:36.495182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e5784b0e64'
down_revision: Union[str, Sequence[str], None] = '4912d6ea2621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'preferences')
    # ### end Alembic commands ###
