"""add time_from and time_to to delivery

Revision ID: 5888d143a790
Revises: 7587c1a3ec9a
Create Date: 2025-07-03 16:25:31.724862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5888d143a790'
down_revision: Union[str, Sequence[str], None] = '7587c1a3ec9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('time_from', sa.String(length=8), nullable=True))
    op.add_column('delivery', sa.Column('time_to', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'time_to')
    op.drop_column('delivery', 'time_from')
    # ### end Alembic commands ###
