"""Initial migration with updated order model

Revision ID: 5c5a0163e3f3
Revises: f9f01d093917
Create Date: 2025-07-05 04:45:05.778984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5a0163e3f3'
down_revision: Union[str, Sequence[str], None] = 'f9f01d093917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('is_subscription', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'is_subscription')
    # ### end Alembic commands ###
