"""add address fields to delivery

Revision ID: 7587c1a3ec9a
Revises: 04cc2bba52aa
Create Date: 2025-07-03 15:43:09.678842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7587c1a3ec9a'
down_revision: Union[str, Sequence[str], None] = '04cc2bba52aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('street', sa.String(length=128), nullable=True))
    op.add_column('delivery', sa.Column('building_number', sa.String(length=32), nullable=True))
    op.add_column('delivery', sa.Column('time_window', sa.String(length=64), nullable=True))
    op.add_column('delivery', sa.Column('size', sa.String(length=32), nullable=True))
    op.add_column('delivery', sa.Column('phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'phone')
    op.drop_column('delivery', 'size')
    op.drop_column('delivery', 'time_window')
    op.drop_column('delivery', 'building_number')
    op.drop_column('delivery', 'street')
    # ### end Alembic commands ###
