"""add price table

Revision ID: 792e2c64fcfc
Revises: fac4184b7cbd
Create Date: 2025-07-03 13:54:47.057507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792e2c64fcfc'
down_revision: Union[str, Sequence[str], None] = 'fac4184b7cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bouquet_size', sa.String(length=16), nullable=False),
    sa.Column('delivery_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bouquet_size', 'delivery_type', name='uq_bouquet_delivery')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    # ### end Alembic commands ###
