"""Initial migration with updated order model

Revision ID: 87aec34d086c
Revises: 298bb0d0d44d
Create Date: 2025-07-23 01:42:44.005939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aec34d086c'
down_revision: Union[str, Sequence[str], None] = '298bb0d0d44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
    op.add_column('courier', sa.Column('telegram_username', sa.String(length=64), nullable=True))
    op.add_column('courier', sa.Column('telegram_registered', sa.Boolean(), nullable=True))
    op.add_column('courier', sa.Column('telegram_notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('courier', sa.Column('last_telegram_activity', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'courier', ['telegram_chat_id'])
    op.add_column('delivery', sa.Column('telegram_notification_sent', sa.Boolean(), nullable=True))
    op.add_column('delivery', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'telegram_message_id')
    op.drop_column('delivery', 'telegram_notification_sent')
    op.drop_constraint(None, 'courier', type_='unique')
    op.drop_column('courier', 'last_telegram_activity')
    op.drop_column('courier', 'telegram_notifications_enabled')
    op.drop_column('courier', 'telegram_registered')
    op.drop_column('courier', 'telegram_username')
    op.drop_column('courier', 'telegram_chat_id')
    # ### end Alembic commands ###
