"""add created_at to order, delivered_at and status_changed_at to delivery

Revision ID: 9f2be47c1a6b
Revises: 3b07d08d6c27
Create Date: 2025-07-03 23:42:56.649245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2be47c1a6b'
down_revision: Union[str, Sequence[str], None] = '3b07d08d6c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('delivery', sa.Column('status_changed_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'created_at')
    op.drop_column('delivery', 'status_changed_at')
    op.drop_column('delivery', 'delivered_at')
    # ### end Alembic commands ###
