"""Add telegram notification fields to delivery

Revision ID: add_telegram_fields
Revises: 17b3b356ac63
Create Date: 2025-07-24 22:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_telegram_fields'
down_revision = '17b3b356ac63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('telegram_notification_sent', sa.Boolean(), nullable=True))
    op.add_column('delivery', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'telegram_message_id')
    op.drop_column('delivery', 'telegram_notification_sent')
    # ### end Alembic commands ### 