"""add settings table

Revision ID: c9faa6152108
Revises: e1e0ca7c91b3
Create Date: 2025-07-05 02:59:18.590265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9faa6152108'
down_revision: Union[str, Sequence[str], None] = 'e1e0ca7c91b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_type'), 'settings', ['type'], unique=False)
    op.create_index(op.f('ix_settings_value'), 'settings', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_value'), table_name='settings')
    op.drop_index(op.f('ix_settings_type'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
