"""Initial migration with updated order model

Revision ID: e1e0ca7c91b3
Revises: 
Create Date: 2025-07-05 01:15:28.141696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e0ca7c91b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('telegram', sa.String(length=128), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('marketing_source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deliveries_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bouquet_size', sa.String(length=16), nullable=False),
    sa.Column('delivery_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bouquet_size', 'delivery_type', name='uq_bouquet_delivery')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=128), nullable=False),
    sa.Column('recipient_phone', sa.String(length=32), nullable=False),
    sa.Column('recipient_social', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('street', sa.String(length=128), nullable=False),
    sa.Column('building_number', sa.String(length=32), nullable=True),
    sa.Column('floor', sa.String(length=16), nullable=True),
    sa.Column('entrance', sa.String(length=16), nullable=True),
    sa.Column('is_pickup', sa.Boolean(), nullable=True),
    sa.Column('delivery_type', sa.String(length=32), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=False),
    sa.Column('custom_amount', sa.Integer(), nullable=True),
    sa.Column('first_delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_day', sa.String(length=16), nullable=False),
    sa.Column('time_from', sa.String(length=8), nullable=True),
    sa.Column('time_to', sa.String(length=8), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('for_whom', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bouquet_size', sa.String(length=16), nullable=True),
    sa.Column('price_at_order', sa.Integer(), nullable=True),
    sa.Column('periodicity', sa.String(length=8), nullable=True),
    sa.Column('preferred_days', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('building_number', sa.String(length=32), nullable=True),
    sa.Column('floor', sa.String(length=16), nullable=True),
    sa.Column('entrance', sa.String(length=16), nullable=True),
    sa.Column('is_pickup', sa.Boolean(), nullable=True),
    sa.Column('time_from', sa.String(length=8), nullable=True),
    sa.Column('time_to', sa.String(length=8), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('bouquet_size', sa.String(length=16), nullable=True),
    sa.Column('delivery_type', sa.String(length=32), nullable=True),
    sa.Column('price_at_delivery', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery')
    op.drop_table('order')
    op.drop_table('price')
    op.drop_table('courier')
    op.drop_table('client')
    # ### end Alembic commands ###
