"""add personal_discount to client

Revision ID: f9f01d093917
Revises: c9faa6152108
Create Date: 2025-07-05 03:13:56.324640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f01d093917'
down_revision: Union[str, Sequence[str], None] = 'c9faa6152108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('personal_discount', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'personal_discount')
    # ### end Alembic commands ###
