"""Initial PostgreSQL migration

Revision ID: initial_postgresql
Revises: 
Create Date: 2025-07-24 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial_postgresql'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create user table
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=256), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('user_type', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    
    # Create client table
    op.create_table('client',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('instagram', sa.String(length=128), nullable=False),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('telegram', sa.String(length=128), nullable=True),
        sa.Column('credits', sa.Integer(), nullable=True),
        sa.Column('marketing_source', sa.String(length=64), nullable=True),
        sa.Column('personal_discount', sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create courier table
    op.create_table('courier',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('phone', sa.String(length=32), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('deliveries_count', sa.Integer(), nullable=True),
        sa.Column('delivery_rate', sa.Integer(), nullable=True),
        sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
        sa.Column('telegram_username', sa.String(length=64), nullable=True),
        sa.Column('telegram_registered', sa.Boolean(), nullable=True),
        sa.Column('telegram_notifications_enabled', sa.Boolean(), nullable=True),
        sa.Column('last_telegram_activity', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone')
    )
    
    # Create order table
    op.create_table('order',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('recipient_name', sa.String(length=128), nullable=False),
        sa.Column('recipient_phone', sa.String(length=32), nullable=False),
        sa.Column('recipient_social', sa.String(length=128), nullable=True),
        sa.Column('city', sa.String(length=64), nullable=False),
        sa.Column('street', sa.String(length=128), nullable=False),
        sa.Column('building_number', sa.String(length=32), nullable=True),
        sa.Column('floor', sa.String(length=16), nullable=True),
        sa.Column('entrance', sa.String(length=16), nullable=True),
        sa.Column('is_pickup', sa.Boolean(), nullable=True),
        sa.Column('delivery_type', sa.String(length=32), nullable=False),
        sa.Column('size', sa.String(length=32), nullable=False),
        sa.Column('custom_amount', sa.Integer(), nullable=True),
        sa.Column('first_delivery_date', sa.Date(), nullable=False),
        sa.Column('delivery_day', sa.String(length=16), nullable=False),
        sa.Column('time_from', sa.String(length=8), nullable=True),
        sa.Column('time_to', sa.String(length=8), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('preferences', sa.Text(), nullable=True),
        sa.Column('for_whom', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('bouquet_size', sa.String(length=16), nullable=True),
        sa.Column('price_at_order', sa.Integer(), nullable=True),
        sa.Column('periodicity', sa.String(length=8), nullable=True),
        sa.Column('preferred_days', sa.String(length=64), nullable=True),
        sa.Column('is_subscription_extended', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create delivery table
    op.create_table('delivery',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('delivery_date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('street', sa.String(length=128), nullable=True),
        sa.Column('building_number', sa.String(length=32), nullable=True),
        sa.Column('floor', sa.String(length=16), nullable=True),
        sa.Column('entrance', sa.String(length=16), nullable=True),
        sa.Column('is_pickup', sa.Boolean(), nullable=True),
        sa.Column('time_from', sa.String(length=8), nullable=True),
        sa.Column('time_to', sa.String(length=8), nullable=True),
        sa.Column('size', sa.String(length=32), nullable=True),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('courier_id', sa.Integer(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(), nullable=True),
        sa.Column('status_changed_at', sa.DateTime(), nullable=True),
        sa.Column('bouquet_size', sa.String(length=16), nullable=True),
        sa.Column('delivery_type', sa.String(length=32), nullable=True),
        sa.Column('price_at_delivery', sa.Integer(), nullable=True),
        sa.Column('is_subscription', sa.Boolean(), nullable=True),
        sa.Column('preferences', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
        sa.ForeignKeyConstraint(['courier_id'], ['courier.id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create settings table
    op.create_table('settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=64), nullable=False),
        sa.Column('value', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create roles table
    op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    # Create user_roles association table
    op.create_table('user_roles',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('roles')
    op.drop_table('settings')
    op.drop_table('delivery')
    op.drop_table('order')
    op.drop_table('courier')
    op.drop_table('client')
    op.drop_table('user')
    # ### end Alembic commands ### 