name: Deploy to Server

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp -r app deploy/
        cp -r migrations deploy/
        cp -r alembic.ini deploy/
        cp -r requirements.txt deploy/
        cp -r docker-compose.yml deploy/
        cp -r Dockerfile deploy/
        cp -r docker-entrypoint.sh deploy/
        cp -r run.py deploy/
        cp -r config.py deploy/
        cp -r init_db.py deploy/
        cp -r create_migration.py deploy/
        cp -r VERSION deploy/
        cp -r CHANGELOG.md deploy/
        cp -r README.md deploy/
        cp -r DEPLOYMENT.md deploy/
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # Create backup
          if [ -d "/home/isakawar1_gmail_com/crmKvitkovaPovnya" ]; then
            cp -r /home/isakawar1_gmail_com/crmKvitkovaPovnya /home/isakawar1_gmail_com/crmKvitkovaPovnya.backup.$(date +%Y%m%d_%H%M%S)
          fi
          
          # Stop existing containers
          cd /home/isakawar1_gmail_com/crmKvitkovaPovnya
          docker-compose down || true
          
          # Remove old directory
          rm -rf /home/isakawar1_gmail_com/crmKvitkovaPovnya
          
          # Create new directory
          mkdir -p /home/isakawar1_gmail_com/crmKvitkovaPovnya
          
          # Copy new files
          cp -r deploy/* /home/isakawar1_gmail_com/crmKvitkovaPovnya/
          
          # Set permissions
          chmod +x /home/isakawar1_gmail_com/crmKvitkovaPovnya/docker-entrypoint.sh
          
          # Start containers
          cd /home/isakawar1_gmail_com/crmKvitkovaPovnya
          docker-compose up -d --build
          
          # Clean up
          rm -rf deploy
          
          echo "Deployment completed successfully!"
          
    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /home/isakawar1_gmail_com/crmKvitkovaPovnya
          docker-compose ps
          echo "Deployment verification completed!" 